server:
  port: 8001
spring:
  application:
    name: ananops-system
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
#mapper:
#  mappers: com.ananops.common.core.dao.MyMapper
#  not-empty: false
#  identity: MYSQL




