spring: 
  redis:
    database: 1
    host: ananops-db-redis
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    gateway:
      #白名单列表
      whiteList: /auth/login,/user/register,/system/v2/api-docs,/imc/v2/api-docs,/amc/v2/api-docs,/mdmc/v2/api-docs,/bmc/v2/api-docs,/mdc/v2/api-docs,/ws/ws,/websocket/v2/api-docs,/system/auth/activeUser/*,/system/auth/register,/system/auth/registerCompany,
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: ananops-auth
          uri: lb://ananops-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: ananops-gen
          uri: lb://ananops-gen
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        # dfs
        - id: ananops-dfs
          uri: lb://ananops-dfs
          predicates:
            - Path=/dfs/**
          filters:
            - StripPrefix=1
        # act
        - id: ananops-activiti
          uri: lb://ananops-activiti
          predicates:
            - Path=/act/**
          filters:
            - StripPrefix=1
        #system 模块
        - id: ananops-system
          uri: lb://ananops-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        #imc 模块
        - id: ananops-imc
          uri: lb://ananops-imc
          predicates:
            - Path=/imc/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # amc 模块
        - id: ananops-amc
          uri: lb://ananops-amc
          predicates:
            - Path=/amc/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # mdmc模块
        - id: ananops-mdmc
          uri: lb://ananops-mdmc
          predicates:
            - Path=/mdmc/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # bmc模块
        - id: ananops-bmc
          uri: lb://ananops-bmc
          predicates:
            - Path=/bmc/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # mdc模块
        - id: ananops-mdc
          uri: lb://ananops-mdc
          predicates:
            - Path=/mdc/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        # websocket模块
        - id: ananops-websocket
          uri: lb:ws://ananops-websocket
          predicates:
            - Path=/ws/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        - id: ananops-websocket
          uri: lb://ananops-websocket
          predicates:
            - Path=/websocket/**
          filters:
            # 限流配置
            - StripPrefix=1
            # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'


